import type { ArchetypeId } from "./archetypes";

export type QuestionType = "single" | "multi" | "text";
export type ScreenType = "intro" | "question" | "insight" | "featured";

export type Option = {
  label: string;
  weights?: Partial<Record<ArchetypeId, number>>;
};

export type Screen =
  | {
      id: string;
      type: "intro" | "insight";
      section: string;
      eyebrow?: string;
      title: string;
      body: string;
    }
  | {
      id: string;
      type: "featured";
      section: string;
      title: string;
      body: string;
      childhoodQuestionId: string;
      sabotageQuestionId: string;
    }
  | {
      id: string;
      type: "question";
      section: string;
      questionType: QuestionType;
      prompt: string;
      helper?: string;
      optional?: boolean;
      options?: Option[];
      placeholder?: string;
    };

const A = { anticipator: 2 } as const;
const P = { performer: 2 } as const;
const H = { harmonizer: 2 } as const;
const Q = { quiter: 2 } as const;

export const questionnaireScreens: Screen[] = [
  {
    id: "orientation",
    type: "intro",
    section: "Orientation",
    eyebrow: "SakanBody Audit",
    title: "Your nervous system learned how to protect you before it knew how to choose.",
    body: "The first 25 years of life, your body was focused on survival. This audit helps you see what protection formed, how it shows up now, and what identity may be emerging beyond it.",
  },
  {
    id: "audit-focus",
    type: "intro",
    section: "Audit Focus",
    title: "We begin with what brought you here.",
    body: "No need to make the answer polished. Let the current loop, longing, or friction show us where the old protection is asking to be understood.",
  },
  {
    id: "age",
    type: "question",
    section: "Audit Focus",
    questionType: "text",
    prompt: "Your current age:",
    placeholder: "Example: 31",
  },
  {
    id: "why-now",
    type: "question",
    section: "Audit Focus",
    questionType: "text",
    prompt: "In one sentence, what made you book this audit right now?",
    placeholder: "I keep feeling...",
  },
  {
    id: "stuck-areas",
    type: "question",
    section: "Audit Focus",
    questionType: "multi",
    prompt: 'Where do you feel most stuck or most "looping" in your life currently?',
    options: [
      { label: "Career / purpose", weights: P },
      { label: "Body / health", weights: Q },
      { label: "Relationships / intimacy", weights: H },
      { label: "Money / receiving", weights: P },
      { label: "Identity / sense of self", weights: Q },
      { label: "Creativity / expression", weights: H },
      { label: "Other" },
    ],
  },
  {
    id: "first-25",
    type: "intro",
    section: "The First 25 Years",
    title: "Now we map the world your body adapted to.",
    body: "Children read more than words. They read pressure, silence, image, fragility, and what must not be needed. This section gives language to the role your younger self learned to play.",
  },
  {
    id: "family-role",
    type: "question",
    section: "The First 25 Years",
    questionType: "multi",
    prompt: "Growing up, what role did you instinctively play in your family?",
    options: [
      { label: "The responsible one", weights: { anticipator: 1, performer: 2 } },
      { label: "The peacemaker", weights: H },
      { label: "The caretaker", weights: H },
      { label: "The achiever / the proof", weights: P },
      { label: "The invisible one", weights: Q },
      { label: "The funny one / the relief", weights: { harmonizer: 1 } },
      { label: "The strong one", weights: { performer: 1, anticipator: 1 } },
      { label: "The problem", weights: { quiter: 1 } },
      { label: "Other" },
    ],
  },
  {
    id: "childhood-truths",
    type: "question",
    section: "The First 25 Years",
    questionType: "multi",
    prompt: "As a child, which of these were true for you?",
    options: [
      { label: "I tried not to be a burden", weights: H },
      { label: "I tried not to add stress to anyone", weights: H },
      { label: "I was the easy one / the good one", weights: H },
      { label: "I learned to read the room before I spoke", weights: { anticipator: 2, harmonizer: 1 } },
      { label: "I kept my problems to myself", weights: Q },
      { label: "I felt responsible for someone else's wellbeing", weights: H },
      { label: "I felt I had to be okay so others could be okay", weights: { harmonizer: 2, performer: 1 } },
      { label: "I grew up faster than I needed to", weights: { performer: 1, anticipator: 1 } },
      { label: "I didn't want to take up space", weights: { harmonizer: 1, quiter: 1 } },
      { label: "I performed being fine", weights: P },
      { label: "Other" },
    ],
  },
  {
    id: "learned-when",
    type: "question",
    section: "The First 25 Years",
    questionType: "text",
    prompt: "Looking at what you selected, when did you first learn to do this? What was happening around you?",
    placeholder: "I first remember...",
  },
  {
    id: "home-climate",
    type: "question",
    section: "The First 25 Years",
    questionType: "single",
    prompt: "What was the emotional climate of your home?",
    options: [
      { label: "Tense / walking on eggshells", weights: A },
      { label: "Cold / disconnected", weights: Q },
      { label: "Chaotic / unpredictable", weights: A },
      { label: "Over-involved / enmeshed", weights: H },
      { label: "Performative / image-focused", weights: P },
      { label: "Warm but conditional", weights: { performer: 1, harmonizer: 1 } },
      { label: "Other" },
    ],
  },
  {
    id: "tracked-wellbeing",
    type: "question",
    section: "The First 25 Years",
    questionType: "multi",
    prompt: "Was there someone in your childhood whose wellbeing you were quietly aware of? Someone whose state you tracked?",
    options: [
      { label: "A parent's health (physical or mental)", weights: { anticipator: 2, harmonizer: 1 } },
      { label: "A parent's mood / emotions", weights: { anticipator: 1, harmonizer: 2 } },
      { label: "A sibling who needed extra care or attention", weights: H },
      { label: "The family's image / reputation", weights: P },
      { label: "The peace of the home", weights: H },
      { label: "A financial situation", weights: A },
      { label: "A grief / loss the family carried", weights: { anticipator: 1, quiter: 1 } },
      { label: "An unspoken tension no one talked about", weights: A },
      { label: "None that I'm aware of" },
      { label: "Other" },
    ],
  },
  {
    id: "unspoken-noticed",
    type: "question",
    section: "The First 25 Years",
    questionType: "text",
    prompt: "Describe what you noticed as a child, even if no one named it out loud. What did you sense was happening that you weren't supposed to talk about?",
  },
  {
    id: "unspoken-rules",
    type: "question",
    section: "The First 25 Years",
    questionType: "multi",
    prompt: "Even in a loving home, children pick up unspoken rules. Which of these did you absorb?",
    options: [
      { label: "Don't make things harder", weights: H },
      { label: "Don't be the reason someone worries", weights: { harmonizer: 2, anticipator: 1 } },
      { label: "Stay small with your needs", weights: { harmonizer: 1, quiter: 1 } },
      { label: "Be the one who's okay", weights: P },
      { label: "Achieve / succeed / make us proud", weights: P },
      { label: "Don't outshine", weights: H },
      { label: "Hold it together", weights: { performer: 1, anticipator: 1 } },
      { label: "Be grateful, don't complain", weights: H },
      { label: "Be useful", weights: P },
      { label: "Be good", weights: H },
      { label: "Don't need too much", weights: { harmonizer: 1, quiter: 1 } },
      { label: "Other" },
    ],
  },
  {
    id: "felt-cost",
    type: "question",
    section: "The First 25 Years",
    questionType: "text",
    prompt: "If you broke this rule as a child, even just imagined breaking it, what did you sense would happen? Not punishment necessarily. Just... what was the felt cost?",
  },
  {
    id: "childhood-movement",
    type: "question",
    section: "The First 25 Years",
    questionType: "multi",
    prompt: "Looking at your childhood self, which of these describe how you moved through the world?",
    options: [
      { label: "Always one step ahead / anticipating", weights: A },
      { label: "Quietly observing before acting", weights: A },
      { label: "Tip-toeing / careful not to disturb", weights: H },
      { label: "Performing okay-ness", weights: P },
      { label: "Caring for others before myself", weights: H },
      { label: "Hyper-organized / hyper-responsible", weights: { anticipator: 1, performer: 2 } },
      { label: "Gentle, not too much, not too loud", weights: H },
      { label: "Mature for my age", weights: P },
      { label: 'The "easy" child', weights: H },
      { label: "Always moving to the next thing", weights: P },
      { label: "Other" },
    ],
  },
  {
    id: "recognize-now",
    type: "question",
    section: "The First 25 Years",
    questionType: "text",
    prompt: "Do you still recognize yourself in any of these? Where?",
  },
  {
    id: "blind-spot",
    type: "intro",
    section: "The Blind Spot",
    title: "Pause for a moment. Your answers are starting to reveal the shape of a protection that once made sense.",
    body: "Now we look at what is hard to stop, even when no one is asking. These are not flaws. They are the body repeating what once helped.",
  },
  {
    id: "hard-to-stop",
    type: "question",
    section: "The Blind Spot",
    questionType: "multi",
    prompt: "Which of these do you find genuinely difficult to stop doing, even when you're tired, even on weekends, even when no one is asking?",
    options: [
      { label: "Planning ahead / running scenarios", weights: A },
      { label: "Mentally to-do listing", weights: { anticipator: 1, performer: 1 } },
      { label: "Checking on people you love", weights: H },
      { label: "Producing / achieving / progressing", weights: P },
      { label: "Improving yourself", weights: P },
      { label: "Anticipating what could go wrong", weights: A },
      { label: "Tracking everyone's mood / needs", weights: H },
      { label: "Optimizing your time", weights: P },
      { label: "Being useful", weights: P },
      { label: "Preparing", weights: A },
      { label: "Tidying / organizing / arranging", weights: A },
      { label: "Other" },
    ],
  },
  {
    id: "body-when-stop",
    type: "question",
    section: "The Blind Spot",
    questionType: "text",
    prompt: "Pick the one that's hardest to stop. What happens in your body when you try?",
  },
  {
    id: "slowing-fear",
    type: "question",
    section: "The Blind Spot",
    questionType: "multi",
    prompt: "When you imagine slowing down completely, no plans, no productivity, no caretaking, no improving, for a full week, what's the first fear that rises?",
    options: [
      { label: "I'll fall behind / lose my edge", weights: P },
      { label: "Something bad will happen to someone I love", weights: A },
      { label: "I'll be seen as lazy / selfish / useless", weights: P },
      { label: "I'll lose myself / disappear", weights: Q },
      { label: "I'll feel everything I've been outrunning", weights: Q },
      { label: "I'll become a burden", weights: H },
      { label: "I won't be loved the same way", weights: H },
      { label: "I won't matter", weights: { performer: 1, quiter: 1 } },
      { label: "I'll get sick", weights: { anticipator: 1, quiter: 1 } },
      { label: "I don't know, but it feels unsafe", weights: A },
      { label: "Other" },
    ],
  },
  {
    id: "as-long-as",
    type: "question",
    section: "The Blind Spot",
    questionType: "text",
    prompt: "Complete this sentence in your own words: As long as I keep _______, then _______ won't happen.",
  },
  {
    id: "present-memory",
    type: "question",
    section: "The Blind Spot",
    questionType: "text",
    prompt: "What is your best memory of a moment where you were fully in the present moment?",
  },
  {
    id: "shadow-intro",
    type: "intro",
    section: "The Shadow Personality",
    title: "Who would you be, had you not needed to be so cautious and protective?",
    body: "This is not a bad shadow. It is exiled aliveness: the self that got benched so the protection could keep running.",
  },
  {
    id: "shadow-clues",
    type: "question",
    section: "The Shadow Personality",
    questionType: "multi",
    prompt: "Which of these have you noticed in yourself? Be honest, these are clues, not flaws.",
    options: [
      { label: "I feel a sharp envy when I see certain women, confident, loud, sensual, free", weights: H },
      { label: 'I am fascinated by women who seem to "get away with" things I never could', weights: H },
      { label: "I have a private fantasy version of myself I never let out", weights: Q },
      { label: 'I sometimes catch myself thinking "if only I were the kind of person who..."', weights: Q },
      { label: "There are things I want that I'd be embarrassed to admit", weights: H },
      { label: "I feel a pull toward luxury, attention, indulgence, or wildness, and immediately judge it", weights: P },
      { label: "I feel more myself in a rare setting, like travel, certain people, alone, or a specific city", weights: Q },
      { label: "There's a version of me that comes out after a drink, on vacation, or with strangers, and I miss her", weights: Q },
      { label: "Other" },
    ],
  },
  {
    id: "shadow-trigger",
    type: "question",
    section: "The Shadow Personality",
    questionType: "text",
    prompt: "Pick the one that hits hardest. Describe what or who specifically triggers it.",
  },
  {
    id: "fascination-shares",
    type: "question",
    section: "The Shadow Personality",
    questionType: "multi",
    prompt: "Looking at the people who fascinate you, or the version of you when feeling safe and welcomed, what do they share?",
    options: [
      { label: "Playful / funny / light", weights: H },
      { label: "Bold / loud / unapologetic", weights: H },
      { label: "Sensual / luxurious / indulgent", weights: P },
      { label: "Soft / receiving / held", weights: H },
      { label: "Wild / free / untamed", weights: Q },
      { label: "Slow / lazy / unproductive", weights: Q },
      { label: "Visible / seen / celebrated", weights: P },
      { label: "Wanting / asking / taking", weights: H },
      { label: "Warm / messy / openly emotional", weights: H },
      { label: "Quiet but unbothered", weights: Q },
      { label: "Other" },
    ],
  },
  {
    id: "dinner-table-feeling",
    type: "question",
    section: "The Shadow Personality",
    questionType: "multi",
    prompt: "If that version of you had shown up at the dinner table as a child, loud, indulgent, demanding, taking up space, wanting things, what's the first feeling you imagine you would have felt?",
    options: [
      { label: "Guilty", weights: H },
      { label: "Selfish", weights: H },
      { label: "Like a burden", weights: H },
      { label: "Out of place", weights: Q },
      { label: "Embarrassed", weights: P },
      { label: "Like I was making things harder", weights: H },
      { label: "Like I was being too much", weights: H },
      { label: "Like I didn't fit the family", weights: Q },
      { label: "Disloyal", weights: H },
      { label: "Other" },
    ],
  },
  {
    id: "shadow-wants",
    type: "question",
    section: "The Shadow Personality",
    questionType: "multi",
    prompt: "What does this shadow self want that you've quietly told yourself is not for you or not who I am?",
    options: [
      { label: "To be visible / celebrated / admired", weights: P },
      { label: "To be wanted / desired / chosen", weights: H },
      { label: "To rest without earning it", weights: { performer: 2, quiter: 1 } },
      { label: "To have luxury / beauty / excess", weights: P },
      { label: "To be taken care of", weights: H },
      { label: "To say no without guilt", weights: H },
      { label: "To want things openly", weights: H },
      { label: "To take up space", weights: H },
      { label: "To be playful / silly / not serious", weights: P },
      { label: "To be selfish sometimes", weights: H },
      { label: "To be soft / receiving", weights: H },
      { label: "To not be useful", weights: P },
      { label: "Other" },
    ],
  },
  {
    id: "most-forbidden",
    type: "question",
    section: "The Shadow Personality",
    questionType: "text",
    prompt: "Pick the one that's most forbidden. What story do you tell yourself about why it's not for you?",
  },
  {
    id: "dreams-intro",
    type: "intro",
    section: "Where Dreams Meet Protection",
    title: "The resistance is the message.",
    body: "Between roughly 25 and 35, protections built in the first 25 years can clash with the life you are now reaching for. What you meet is not your limit. It may be the edge of an old contract.",
  },
  {
    id: "life-window",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "single",
    prompt: "Where are you in this window?",
    options: [
      { label: "I'm 25-30 and just starting to feel the clash" },
      { label: "I'm 30-35 and I'm in the thick of it" },
      { label: "I'm 35-40 and I'm late to seeing it but I see it now" },
      { label: "I'm past 40 and these patterns went unaddressed for years" },
      { label: "I'm under 25 and I'm noticing it early" },
      { label: "Other" },
    ],
  },
  {
    id: "looping-dream-areas",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "multi",
    prompt: "In which of these areas have you been looping, wanting something, reaching for it, and finding yourself blocked or sabotaging?",
    options: [
      { label: "A career move / business / creative project", weights: P },
      { label: "A relationship I want (or want to leave)", weights: H },
      { label: "My body / health / weight / energy", weights: Q },
      { label: "Money / receiving / charging more", weights: P },
      { label: "Visibility / putting myself out there", weights: { performer: 1, harmonizer: 1 } },
      { label: "A creative dream I keep almost starting", weights: Q },
      { label: "Moving / a place I want to live", weights: A },
      { label: "Becoming a mother / not becoming one", weights: H },
      { label: "A version of myself I keep almost becoming", weights: Q },
      { label: "Other" },
    ],
  },
  {
    id: "specific-dream",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "text",
    prompt: "Pick the area that's most charged. Now describe the dream itself in detail. Not the obstacle, the dream. What would your life actually look like if it were real?",
  },
  {
    id: "sabotage-mechanism",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "multi",
    prompt: "When you get close to this dream, which of these tends to happen? Be honest. Most people do at least three of these.",
    options: [
      { label: "I get sick / exhausted / depleted", weights: Q },
      { label: "I get distracted / scattered / lose focus", weights: Q },
      { label: 'I procrastinate or "research" instead of doing', weights: { quiter: 1, anticipator: 1 } },
      { label: 'I shrink the dream / make it smaller / "be realistic"', weights: H },
      { label: "I sabotage relationships that would support it", weights: H },
      { label: "I pick fights / create drama", weights: A },
      { label: "I become hyper-busy with other things", weights: P },
      { label: "I doubt myself into paralysis", weights: A },
      { label: "I tell myself it's not the right time", weights: Q },
      { label: "I caretake someone else's needs instead", weights: H },
      { label: "I get suddenly very tired / want to sleep", weights: Q },
      { label: "I find a financial reason to stop / anxiety over expenses or debts", weights: A },
      { label: "I lose interest right at the threshold", weights: Q },
      { label: "Other" },
    ],
  },
  {
    id: "dream-protection-match",
    type: "featured",
    section: "Where Dreams Meet Protection",
    title: "The match-up",
    body: "Look at how you protected yourself as a child, then look at how the dream gets blocked now. Often, they are the same protection in a new dress.",
    childhoodQuestionId: "childhood-movement",
    sabotageQuestionId: "sabotage-mechanism",
  },
  {
    id: "body-data",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "text",
    prompt: "When you imagine actually having this dream, fully having it, no caveats, what happens in your body? Where does it tighten, freeze, race, or go numb?",
    helper: "Simply notice. Nothing needs to be treated or changed right now.",
  },
  {
    id: "dream-shield",
    type: "question",
    section: "Where Dreams Meet Protection",
    questionType: "multi",
    prompt: "When you imagine having this dream fully, what's the fear underneath? Check anything that resonates, even faintly.",
    options: [
      { label: "I'd lose connection with the people I love", weights: H },
      { label: "I'd be too visible / too much / too seen", weights: H },
      { label: "I'd outgrow my family / outshine them", weights: { harmonizer: 1, performer: 1 } },
      { label: "I'd be a burden / a target / resented", weights: A },
      { label: "I'd betray someone", weights: H },
      { label: "I'd be punished by life / something would be taken", weights: A },
      { label: "I'd be exposed as a fraud", weights: P },
      { label: "I'd have to feel everything I've been outrunning / responsibility", weights: Q },
      { label: "I wouldn't know who I am anymore", weights: Q },
      { label: 'I would lose my "safe" identity', weights: Q },
      { label: "I don't know, but it feels dangerous", weights: A },
      { label: "Other" },
    ],
  },
  {
    id: "system-expiration",
    type: "intro",
    section: "System Expiration",
    title: "What is true now that was not true then?",
    body: "Your nervous system built its protection based on the reality of childhood. The question now is not whether the protection worked. It did. The question is whether the conditions are still the same.",
  },
  {
    id: "current-resources",
    type: "question",
    section: "System Expiration",
    questionType: "multi",
    prompt: "Which of these are true in your life today, even if you don't always feel them?",
    options: [
      { label: "I can financially support myself (or have access to support)" },
      { label: "I can leave a situation that doesn't feel right" },
      { label: "I have at least one person I can be honest with" },
      { label: "I can say no, even if it's hard" },
      { label: "I have a body that has carried me through real things" },
      { label: "I have skills, knowledge, or experience I've earned" },
      { label: "I can ask for help (even imperfectly)" },
      { label: "I can be alone without it being unsafe" },
      { label: "I can choose where I live, who I'm with, how I spend my time" },
      { label: "I have language for what I feel (more than I did as a child)" },
      { label: "I'm no longer dependent on the people I had to protect myself from" },
      { label: "I have more agency over my body, my time, my decisions" },
      { label: "Other" },
    ],
  },
  {
    id: "resources-body",
    type: "question",
    section: "System Expiration",
    questionType: "text",
    prompt: "Read your selections back to yourself slowly. What do you notice in your body?",
    helper: "Simply notice. Nothing needs to be treated or changed right now.",
  },
  {
    id: "external-changes",
    type: "question",
    section: "System Expiration",
    questionType: "multi",
    prompt: "Compared to the environment you grew up in, which of these have changed?",
    options: [
      { label: "The person whose wellbeing I tracked is no longer my responsibility (or is no longer here)" },
      { label: "I'm no longer living in that home" },
      { label: "The financial situation is different" },
      { label: "The family dynamic has shifted" },
      { label: "I have my own home / space / room" },
      { label: "I have relationships I chose, not just the ones I was born into" },
      { label: "The fear I lived with as a child is no longer present in my daily life" },
      { label: "The danger / fragility / illness that shaped me is no longer the air I breathe" },
      { label: "I have distance, physical, emotional, or both, from the original conditions" },
      { label: "Other" },
    ],
  },
  {
    id: "child-impossible",
    type: "question",
    section: "System Expiration",
    questionType: "text",
    prompt: "Optional: What's one thing about your current life that the child-you couldn't have imagined would be possible?",
    optional: true,
  },
  {
    id: "capacities-built",
    type: "question",
    section: "System Expiration",
    questionType: "multi",
    prompt: "Which of these can you do now that you couldn't do as a child?",
    options: [
      { label: "Recognize when something doesn't feel right" },
      { label: "Walk away from people who harm me" },
      { label: "Set a limit (even if I'm still practicing)" },
      { label: "Soothe myself when I'm activated" },
      { label: "Identify what I'm feeling" },
      { label: "Ask a question instead of assuming" },
      { label: "Repair after a rupture" },
      { label: "Choose who gets access to me" },
      { label: "Tolerate someone being disappointed in me" },
      { label: "Sit with discomfort without immediately fixing it" },
      { label: "Other" },
    ],
  },
  {
    id: "child-changed-everything",
    type: "question",
    section: "System Expiration",
    questionType: "text",
    prompt: "Optional: Which of these would have changed everything for child-you?",
    optional: true,
  },
  {
    id: "somatic-recognition",
    type: "question",
    section: "System Expiration",
    questionType: "single",
    prompt: "After reading through what you just selected, resources, changes, capacities, what's the first thing you notice in your body?",
    options: [
      { label: "A softening, a small relief" },
      { label: "Something doesn't believe it yet, but my mind sees it" },
      { label: "Tears, or something that wants to release" },
      { label: "Resistance, like my body doesn't trust this" },
      { label: "Surprise, I hadn't really seen all of this before" },
      { label: 'A quiet "oh"' },
      { label: "I don't feel anything yet, I want to explore this in session" },
      { label: "Other" },
    ],
  },
  {
    id: "updated-self",
    type: "question",
    section: "System Expiration",
    questionType: "text",
    prompt: "Given everything you've witnessed about your current reality, who would you be if your nervous system updated to match your present life? Describe her.",
  },
  {
    id: "honoring-intro",
    type: "intro",
    section: "Honoring the Protection",
    title: "You do not fire a part of yourself. You promote it.",
    body: "The protection was not a flaw. It was an intelligent response to conditions you did not choose. Now we thank what it gave you and update what it no longer needs to carry.",
  },
  {
    id: "protection-accomplished",
    type: "question",
    section: "Honoring the Protection",
    questionType: "multi",
    prompt: "Looking back, what did this protection actually accomplish for you? Which of these are true?",
    options: [
      { label: "It kept me safe in a situation I couldn't have changed" },
      { label: "It let me get through childhood with my dignity intact" },
      { label: "It helped me become responsible / capable" },
      { label: "It gave me a sense of agency when I had none" },
      { label: "It protected someone I loved" },
      { label: "It earned me the love or peace I needed" },
      { label: "It got me out / got me here" },
      { label: "It built a life I'm now actually able to live in" },
      { label: "It made me someone people can count on" },
      { label: "It gave me a way to be useful when I felt powerless" },
      { label: "Other" },
    ],
  },
  {
    id: "strengths-forged",
    type: "question",
    section: "Honoring the Protection",
    questionType: "multi",
    prompt: "This protection forged real capacities. Which of these did it build in you?",
    options: [
      { label: "Deep attunement to others", weights: H },
      { label: "Ability to read a room instantly", weights: A },
      { label: "Reliability / follow-through", weights: P },
      { label: "Emotional sensitivity", weights: H },
      { label: "Empathy", weights: H },
      { label: "Maturity / depth", weights: P },
      { label: "Resilience", weights: Q },
      { label: "Anticipation / foresight", weights: A },
      { label: "Ability to hold complexity", weights: A },
      { label: "Capacity to show up for others", weights: H },
      { label: "Discipline", weights: P },
      { label: "Self-sufficiency", weights: Q },
      { label: "Inner steadiness under pressure", weights: A },
      { label: "Other" },
    ],
  },
  {
    id: "strengths-keep",
    type: "question",
    section: "Honoring the Protection",
    questionType: "text",
    prompt: "Which of these would you not want to lose, even as the protection itself softens?",
  },
  {
    id: "jobs-done",
    type: "question",
    section: "Honoring the Protection",
    questionType: "multi",
    prompt: "Now that your life has changed, which of these jobs does the protection no longer need to do?",
    options: [
      { label: "Track everyone's mood for safety reasons", weights: H },
      { label: "Anticipate danger that isn't there", weights: A },
      { label: "Earn love that's already given", weights: P },
      { label: "Prevent abandonment that isn't coming", weights: H },
      { label: "Hold the family together", weights: H },
      { label: "Protect a parent who is no longer fragile (or no longer here)", weights: A },
      { label: "Stay small so others can be big", weights: H },
      { label: "Be useful in order to be allowed to exist", weights: P },
      { label: "Perform okay-ness when I'm not okay", weights: P },
      { label: "Carry weight that wasn't mine to carry", weights: Q },
      { label: "Other" },
    ],
  },
  {
    id: "jobs-reflection",
    type: "question",
    section: "Honoring the Protection",
    questionType: "text",
    prompt: "What's it like to consider that the protection is still doing jobs no one is asking it to do anymore?",
  },
  {
    id: "promotion",
    type: "question",
    section: "Honoring the Protection",
    questionType: "multi",
    prompt: "If the protection were promoted to a new role, one that fits your current life rather than your past, which of these feels right?",
    options: [
      { label: "From hyper-vigilance to discernment", weights: A },
      { label: "From caretaking everyone to caring for what's actually mine", weights: H },
      { label: "From productivity-as-survival to creation as expression", weights: P },
      { label: "From perfectionism to craft", weights: P },
      { label: "From people-pleasing to genuine generosity", weights: H },
      { label: "From self-sufficiency to interdependence", weights: Q },
      { label: "From anticipating danger to sensing aliveness", weights: A },
      { label: "From holding it together to letting things move through me", weights: Q },
      { label: "From earning love to receiving love", weights: P },
      { label: "From staying small to taking up the space that's mine", weights: H },
      { label: "Other" },
    ],
  },
  {
    id: "thank-protection",
    type: "question",
    section: "Honoring the Protection",
    questionType: "text",
    prompt: "Write a sentence to your protection, not to dismiss it, but to thank it and update its role.",
    placeholder: "Thank you for keeping me safe. You can now...",
  },
  {
    id: "identity-intro",
    type: "intro",
    section: "Identity Inquiry",
    title: "Who are you outside this protection?",
    body: "We are not trying to force an answer. The not-knowing is not a problem. It is the doorway. Let it stay open for a while.",
  },
  {
    id: "quiet-protection",
    type: "question",
    section: "Identity Inquiry",
    questionType: "multi",
    prompt: "Think of moments, even brief ones, when the protection has gone quiet. In those moments, what's true about you?",
    options: [
      { label: "I'm slower", weights: Q },
      { label: "I'm warmer", weights: H },
      { label: "I'm funnier", weights: H },
      { label: "I'm quieter", weights: Q },
      { label: "I'm more sensual", weights: H },
      { label: "I'm more curious", weights: A },
      { label: "I'm more playful", weights: P },
      { label: "I'm more direct", weights: H },
      { label: "I'm more affectionate", weights: H },
      { label: "I'm more spacious", weights: Q },
      { label: "I'm more present", weights: A },
      { label: "I'm more honest", weights: H },
      { label: "I notice things I usually miss", weights: A },
      { label: "I don't know, I'm not sure I've felt that" },
      { label: "Other" },
    ],
  },
  {
    id: "quiet-moment-detail",
    type: "question",
    section: "Identity Inquiry",
    questionType: "text",
    prompt: "Describe one of these moments in detail. Where were you, who were you with, what did your body feel like?",
  },
  {
    id: "never-tested",
    type: "question",
    section: "Identity Inquiry",
    questionType: "multi",
    prompt: "Which of these have you never really been able to test, because the protection has always been running?",
    options: [
      { label: "Whether I'd actually be loved if I weren't useful", weights: P },
      { label: "Whether I'd be safe if I weren't perfect", weights: P },
      { label: "Whether anyone would stay if I were difficult", weights: H },
      { label: "Whether I could rest without falling apart", weights: Q },
      { label: "Whether I could want something openly without losing it", weights: H },
      { label: "Whether I could be wrong and still be okay", weights: P },
      { label: "Whether I could disappoint someone and survive it", weights: H },
      { label: "Whether I could be slow without being left behind", weights: Q },
      { label: "Whether I could be soft without being crushed", weights: H },
      { label: "Whether I could need without being a burden", weights: H },
      { label: "Whether I could just be without earning it", weights: P },
      { label: "Other" },
    ],
  },
  {
    id: "scary-test",
    type: "question",
    section: "Identity Inquiry",
    questionType: "text",
    prompt: "Pick the one that scares you most to test. Why?",
  },
  {
    id: "outside-image",
    type: "question",
    section: "Identity Inquiry",
    questionType: "single",
    prompt: "When you imagine the version of you outside the protection, which is more honest?",
    options: [
      { label: "I have a clear, vivid image of her" },
      { label: "I have a vague sense but I can't really feel her" },
      { label: "I have an image but I suspect it's still a performance" },
      { label: "I genuinely don't know who I am underneath" },
      { label: "I'm afraid there's nothing underneath" },
      { label: "I've glimpsed her but I don't trust it yet" },
      { label: "Other" },
    ],
  },
  {
    id: "not-knowing",
    type: "question",
    section: "Identity Inquiry",
    questionType: "single",
    prompt: "How does it feel to consider that you might not need to have an answer to who am I outside this protection yet?",
    options: [
      { label: "A relief, I've been pressuring myself to know" },
      { label: "Uncomfortable but okay" },
      { label: "Hard, I want an answer" },
      { label: "Scary, I feel ungrounded without one" },
      { label: "I want to explore this in session" },
      { label: "Other" },
    ],
  },
  {
    id: "small-evidence",
    type: "question",
    section: "Identity Inquiry",
    questionType: "text",
    prompt: "What's one small thing, a feeling, a moment, a glimpse, that already hints at who you might be underneath the protection?",
  },
  {
    id: "finding-out-fear",
    type: "question",
    section: "Identity Inquiry",
    questionType: "multi",
    prompt: "What's underneath the resistance to meeting this version of yourself?",
    options: [
      { label: "I'm afraid she'll be disappointing" },
      { label: "I'm afraid she'll be too much" },
      { label: "I'm afraid she won't be loved the same way" },
      { label: "I'm afraid she'll outgrow people I love" },
      { label: "I'm afraid she'll be selfish" },
      { label: "I'm afraid I won't recognize her" },
      { label: "I'm afraid she'll make me grieve who I've been" },
      { label: "I'm afraid I'll have to change my life in ways I'm not ready for" },
      { label: "I'm afraid I won't be able to go back" },
      { label: "I'm afraid she'll be the same as the protected one and I'll have done all this for nothing" },
      { label: "Other" },
    ],
  },
  {
    id: "grief",
    type: "question",
    section: "Identity Inquiry",
    questionType: "text",
    prompt: "What might you have to grieve if you stop running the protection? Who or what would you be saying goodbye to?",
  },
  {
    id: "closing-recognition",
    type: "question",
    section: "Identity Inquiry",
    questionType: "text",
    prompt: "Write one sentence to the version of you who is just beginning to come online. Not a promise. Not a goal. Just a small acknowledgment.",
    placeholder: "I see you. Take your time.",
  },
];

export const questionScreens = questionnaireScreens.filter(
  (screen) => screen.type === "question",
) as Extract<Screen, { type: "question" }>[];

export const totalQuestionCount = questionScreens.length;
